name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy-reusably:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."